/* Legal page content — carried over from the live site, preserved faithfully.
   Each policy is an array of blocks: {t:'h'} heading, {t:'p'} paragraph, {t:'rule'} divider. */
window.LEGAL = {
  privacy: {
    title: "Privacy Policy",
    updated: "Effective: aligned with GDPR Art. 13/14 (Regulation (EU) 2016/679)",
    intro: "Please read this Privacy Policy carefully before accessing, using or obtaining any materials, information, products or services. This policy applies to the BLACKFOX DIGITAL website, which is the property of Blackfox Digital and its licensors. By using the site you agree to be bound by this Privacy Policy. Blackfox Digital reserves the right, at its sole discretion, to change, modify, add or remove portions of this policy at any time, and it is the responsibility of the user to check periodically for changes.",
    blocks: [
      { t: "h", x: "Types of data gathered" },
      { t: "p", x: "This website saves types of personal data, by itself or through third parties, like Cookies, Usage Data, first name, last name, email address, data communicated while using the service, country, various types of date, website, and portfolio link." },
      { t: "p", x: "Personal Data may be freely provided by the User, or, in the case of Usage Data, collected automatically when using this website. Unless specified otherwise, all data requested by this website is mandatory and failure to provide it may make it impossible for this website to provide its services." },
      { t: "p", x: "Users are responsible for any third-party Personal Data obtained, published or shared through this website and confirm that they have the third party's consent to provide the data to the Owner." },

      { t: "h", x: "Mode and place of processing the data" },
      { t: "p", x: "The purposes of processing. The data concerning the User is collected to allow the Owner to provide its services, as well as for: Analytics, Contacting the User, Displaying content from external platforms, Interaction with live chat platforms, Managing contacts and sending messages, and Handling payments." },
      { t: "p", x: "Methods of processing. The Owner takes appropriate security measures to prevent unauthorized access, disclosure, modification, or unauthorized destruction of the data. Processing is carried out using computers and/or IT-enabled tools, following organizational procedures strictly related to the purposes indicated." },
      { t: "p", x: "Legal basis of processing. The Owner may process Personal Data relating to Users where consent has been given; where provision is necessary for the performance of an agreement; for compliance with a legal obligation; for a task carried out in the public interest; or for the purposes of the legitimate interests pursued by the Owner or a third party." },
      { t: "p", x: "Retention time. Personal Data shall be processed and stored for as long as required by the purpose it was collected for. Once the retention period expires, Personal Data shall be deleted." },
      { t: "p", x: "Place. The data is processed at the Owner's operating offices and in any other places where the parties involved in the processing are located. Depending on the User's location, data transfers may involve transferring data to a country other than their own." },

      { t: "h", x: "Detailed information on the processing of Personal Data" },
      { t: "sub", x: "Contacting the User" },
      { t: "p", x: "Contact form — by filling in the contact form with their data, the User authorizes this website to use these details to reply to requests for information, quotes or any other kind of request. Personal Data collected: first name, last name, email address." },
      { t: "p", x: "Mailing list / newsletter — by registering, the User's email address will be added to the contact list of those who may receive commercial or promotional messages. Personal Data collected: email address, first name, last name." },
      { t: "sub", x: "Analytics" },
      { t: "p", x: "Google Analytics (Google Inc.) — a web analysis service that tracks and examines the use of this website to prepare reports on its activities. Personal Data collected: Cookies and Usage Data. Place of processing: United States." },
      { t: "p", x: "Facebook Ads conversion tracking (Facebook, Inc.) — connects data from the Facebook advertising network with actions performed on this website. Personal Data collected: Cookies and Usage Data." },
      { t: "sub", x: "Displaying content from external platforms" },
      { t: "p", x: "Google Fonts (Google Inc.) — a typeface visualization service that allows this website to incorporate fonts on its pages. Personal Data collected: Usage Data and various types of data as specified in the service's privacy policy." },
      { t: "sub", x: "Interaction with live chat & contact management" },
      { t: "p", x: "Tawk.to (Tawk.to Inc.) — a live chat platform. eSputnik (eSputnik Inc.) — an email management and message sending service. Personal Data collected: Cookies, data communicated while using the service, and Usage Data." },

      { t: "h", x: "The rights of Users" },
      { t: "p", x: "Users may withdraw consent at any time; object to processing of their data; access their data; verify and seek rectification; restrict processing; have their Personal Data deleted; receive their data and have it transferred to another controller; and lodge a complaint with their competent data protection authority." },
      { t: "p", x: "How to exercise these rights — any requests can be directed to the Owner through the contact details provided. Requests can be exercised free of charge and will be addressed as early as possible, always within one month." },

      { t: "h", x: "Additional information" },
      { t: "p", x: "Legal action. The User's Personal Data may be used for legal purposes by the Owner in court or in the stages leading to possible legal action arising from improper use of this website." },
      { t: "p", x: "System logs and maintenance. This website and any third-party services may collect files that record interaction with this website (system logs) and other Personal Data such as the IP address for this purpose." },
      { t: "p", x: "Changes to this privacy policy. The Owner reserves the right to make changes at any time by giving notice on this page. It is strongly recommended to check this page often." },
      { t: "p", x: "Definitions. Personal Data, Usage Data, Data Processor, User, Data Subject, Data Controller (Owner), Cookies, and Service carry their standard GDPR meanings. This statement has been prepared based on multiple legislations, including Art. 13/14 of Regulation (EU) 2016/679 (GDPR)." },
    ],
  },

  terms: {
    title: "Terms & Conditions",
    updated: "Published Oct 25, 2019 · Governed by English law",
    intro: "Please read our Terms and Conditions of Use (\u201CTerms\u201D) and Privacy Policy carefully because they affect your legal rights, including an agreement to resolve any disputes that may arise between us. By signing up or otherwise using the Blackfox Digital website and services, you are entering into a binding contract with Blackfox Digital.",
    blocks: [
      { t: "num", n: "1", x: "Introduction", b: "By visiting, using or engaging with our website and services, you are entering into a binding contract with Blackfox Digital. Your agreement includes these Terms and our Privacy Policy. To use the service you must be 18 or older (or 13+ with parental consent), have the power to enter a binding contract, and reside in a country where the site is available." },
      { t: "num", n: "2", x: "Changes to the Agreements", b: "Occasionally we may make changes to the Agreements. It is your responsibility to check periodically. Your continued use following the posting of changes means you accept them." },
      { t: "num", n: "3", x: "Site Limitations & Modifications", b: "We make reasonable efforts to keep the site operational, but technical difficulties or maintenance may result in temporary interruptions. We reserve the right to modify or discontinue features, with or without notice, to the extent permitted by law." },
      { t: "num", n: "4", x: "Using the Site", b: "Here's some information about all the ways you can use the site, set out in the sections that follow." },
      { t: "num", n: "5", x: "Our Services", b: "Blackfox Digital provides retouch, clipping path and other Photoshop services. We require full payment when you submit your order, unless otherwise agreed. You can request a quote before purchasing." },
      { t: "num", n: "6", x: "Third Party Applications", b: "We integrate with third-party applications and services (e.g. Shopify, PayPal, Stripe). These have their own terms and privacy policies. We do not endorse and are not responsible for the behavior, features or content of any third-party application." },
      { t: "num", n: "7", x: "User-Generated Content", b: "You may post content to obtain services. You promise you have the right to post such content and that it does not violate the Agreements or the rights of others. We may, but have no obligation to, monitor, review or edit User Content, and may remove it at our discretion. You are solely responsible for all User Content you provide." },
      { t: "num", n: "8", x: "Rights You Grant Us", b: "Unless you advise us otherwise in writing, you agree we may use your images on our website and in our marketing materials. If you provide feedback, ideas or suggestions, you authorize us to use that feedback without restriction and without payment." },
      { t: "num", n: "9", x: "User Guidelines", b: "We respect intellectual property rights and expect you to do the same. Copying, redistributing, reverse-engineering, reselling, circumventing protections, removing notices, sharing passwords or scraping the service is not permitted. You are responsible for keeping your password confidential and for all use of your account." },
      { t: "num", n: "10", x: "Intellectual Property", b: "All content on the site \u2014 text, graphics, logos, images, data compilations and software \u2014 is the property of Blackfox Digital or its suppliers and is protected by copyright law. You may print or download extracts for personal, non-commercial use only. To report infringement, contact info@blackfoxdigital.com.bd." },
      { t: "num", n: "11", x: "Customer Support", b: "For account- and payment-related questions, contact info@blackfoxdigital.com.bd. We will use reasonable endeavors to respond within a reasonable time frame." },
      { t: "num", n: "12", x: "Payments, Refunds & Cancellations", b: "Individual clients pay in full upfront before work begins (PayPal, credit card, Edit Credits, bank transfer). Corporate clients may be extended credit subject to checks. Revisions and refund requests must be made within 14 days of delivery; if edited images follow the same quality standard as an approved sample, we cannot refund that order. Prices may vary and you'll see the price before confirming any new order." },
      { t: "num", n: "13", x: "Quotes and Orders", b: "If the image of a client's order does not match the sample provided with the original quote, the order may be canceled and a new quote provided for a separate order." },
      { t: "num", n: "14", x: "Turnaround Time", b: "When a client selects a turnaround time, that time begins after the client has finished uploading all images to be edited \u2014 not when the order is submitted." },
      { t: "num", n: "15", x: "Term and Termination", b: "The Agreements continue until terminated by either party. We may terminate or suspend access at any time, including for unauthorized use or non-compliance. You may terminate at any time by contacting info@blackfoxdigital.com.bd." },
      { t: "num", n: "16", x: "Warranty and Disclaimer", b: "The site is provided \u201Cas is\u201D and \u201Cas available\u201D, without express or implied warranty of any kind. You use the service at your own risk. This does not affect your statutory rights as a consumer." },
      { t: "num", n: "17", x: "Limitations", b: "To the extent permitted by law, your sole and exclusive remedy for any dissatisfaction with the service is to stop using the site. Aggregate liability for all claims will not exceed the amounts paid by you in the prior twelve months." },
      { t: "num", n: "18", x: "Third-Party Rights", b: "Owners of the content and certain distributors are intended beneficiaries of the Agreements and may enforce them directly against you. Otherwise, the Agreements do not create third-party beneficiary rights." },
      { t: "num", n: "19", x: "Entire Agreement", b: "The Agreements constitute all terms agreed between you and Blackfox Digital and supersede any prior agreements relating to their subject matter." },
      { t: "num", n: "20", x: "Severability and Waiver", b: "Should any provision be held invalid or unenforceable, the remaining provisions remain in effect. Failure to enforce a provision does not waive the right to do so." },
      { t: "num", n: "21", x: "Assignment", b: "Blackfox Digital may assign the Agreements or delegate obligations. You may not assign or sub-license your rights to any third party." },
      { t: "num", n: "22", x: "Applicable Law", b: "The Agreements are governed by and interpreted under English law. You agree to submit to the exclusive jurisdiction of the English courts." },
      { t: "num", n: "23", x: "Indemnification", b: "To the fullest extent permitted by law, you agree to indemnify and hold Blackfox Digital harmless from damages, losses and expenses arising out of your breach, your User Content, your activity on the site, or your violation of any law or third-party right." },
      { t: "num", n: "24", x: "Privacy", b: "Our current Privacy Policy is available on the site and incorporated by reference. We strongly recommend you review it closely." },
      { t: "num", n: "25", x: "Cookies", b: "A cookie is a small file placed on your device that helps analyze web traffic and remember your preferences. We use traffic-log cookies for statistical analysis. Blocking all cookies may negatively impact the usability of many websites." },
      { t: "num", n: "26", x: "Contact Us", b: "If you have any questions concerning the service or the Agreements, contact Customer Service at info@blackfoxdigital.com.bd." },
    ],
  },

  cookies: {
    title: "Cookies Policy",
    updated: "How Blackfox Digital uses cookies",
    intro: "This Cookies Policy explains the portions of code installed in the browser that assist the Owner in delivering the service. Some purposes for which Cookies are installed may require the User's agreement. Where installation is based on consent, such consent can be freely withdrawn at any time following the instructions described here.",
    blocks: [
      { t: "h", x: "Technical & statistical cookies" },
      { t: "p", x: "Strictly necessary — this website uses Cookies to save the User's session and carry out other activities essential for its operation, for example in relation to the distribution of traffic." },
      { t: "p", x: "Preferences, optimization & statistics — Cookies save browsing preferences (such as language and currency choice) and manage first-party statistics. \u201CSession\u201D cookies (PHPSESSID, lang_id, lang_code) are deleted when you close your browser. \u201CPersistent\u201D cookies remain until deleted or until they expire." },

      { t: "h", x: "Third-party cookies" },
      { t: "sub", x: "Interaction with live chat platforms" },
      { t: "p", x: "Tawk.to (Tawk.to Inc.) — a live chat platform. Personal Data collected: Cookies, data communicated while using the service, and Usage Data. Cookies used: TawkConnectionTime, __tawkuuid." },
      { t: "sub", x: "SPAM protection" },
      { t: "p", x: "Google reCAPTCHA (Google Inc.) — a SPAM protection service. Use of reCAPTCHA is subject to the Google privacy policy and terms. Personal Data collected: Cookies and Usage Data." },
      { t: "sub", x: "Analytics" },
      { t: "p", x: "Facebook Ads conversion tracking (Facebook, Inc.) — links advertising data with actions on this website. Cookies used: xs, wd, dpr, act, sb, pl, c_user." },
      { t: "p", x: "Google Analytics & Google Tag Manager (Google Inc.) — tracks and studies use of this website to prepare reports. Cookies used: _gid, _ga, APISID, HSID, NID, SAPISID, SID, SIDCC, SSID. You can opt out at tools.google.com/dlpage/gaoptout." },
      { t: "p", x: "Yandex Metrika (Yandex) — a web analysis system. Cookies used: _ym_d, _ym_uid, _ym_isad. Place of processing: Moscow, Russia." },

      { t: "h", x: "Providing or withdrawing consent" },
      { t: "p", x: "You can manage preferences for Cookies directly from within your own browser and stop third parties installing Cookies. Through browser preferences you can also remove Cookies installed in the past. For third-party Cookies, you may use the related opt-out link or contact the third party directly." },
      { t: "p", x: "You may also follow the instructions provided by the EDAA (EU), the Network Advertising Initiative (US), the Digital Advertising Alliance (US), DAAC (Canada) or DDAI (Japan) to choose your tracking preferences for most advertising tools." },
    ],
  },
};
