/* Shared content for the BLACKFOX prototype — mirrors the real site's pages & URLs */
export const BF = {
  phone:  "+8801924482868",
  phone2: "+8801841482868",
  email:  "info@blackfoxdigital.com.bd",
  addresses: [
    { country: "Bangladesh", phone: "+8801924482868", lines: ["House 560, Road 08", "Adabor, Dhaka 1207"] },
  ],

  // before/after pairs — every pair uses matched images from the same shoot
  pairs: {

  port_0: { before: "/ecommerce-jacket-before.webp", after: "/ecommerce-jacket-after.webp" },
  port_1: { before: "/ecommerce-headphones-before.webp", after: "/ecommerce-headphones-after.webp" },
  port_2: { before: "/ecommerce-cosmetic-before.webp", after: "/ecommerce-cosmetic-after.webp" },
  port_3: { before: "/ECommerce.jpg", after: "/ECommerce-Done.jpg" },
  port_4: { before: "/bg-removal-hero-before.webp", after: "/bg-removal-hero-after.webp" },
  port_5: { before: "/bg-removal-hair-before.webp", after: "/bg-removal-hair-after.webp" },
  port_6: { before: "/bg-removal-whisk-before.webp", after: "/bg-removal-whisk-after.webp" },
  port_7: { before: "/bg-removal-fur-before.webp", after: "/bg-removal-fur-after.webp" },
  port_8: { before: "/bg-removal-glass-before.webp", after: "/bg-removal-glass-after.webp" },
  port_9: { before: "/clipping-path-espresso-before.webp", after: "/clipping-path-espresso-after.webp" },
  port_10: { before: "/clipping-path-shoe-before.webp", after: "/clipping-path-shoe-after.webp" },
  port_11: { before: "/clipping-path-lens-before.webp", after: "/clipping-path-lens-after.webp" },
  port_12: { before: "/clipping-path-bag-before.webp", after: "/clipping-path-bag-after.webp" },
  port_13: { before: "/ghost-mannequin-hero-before.webp", after: "/ghost-mannequin-hero-after.webp" },
  port_14: { before: "/ghost-mannequin-leather-before.webp", after: "/ghost-mannequin-leather-after.webp" },
  port_15: { before: "/ghost-mannequin-blazer-before.webp", after: "/ghost-mannequin-blazer-after.webp" },
  port_16: { before: "/ghost-mannequin-activewear-before.webp", after: "/ghost-mannequin-activewear-after.webp" },
  port_17: { before: "/ghost-mannequin-gown-before.webp", after: "/ghost-mannequin-gown-after.webp" },
  port_18: { before: "/image-masking-hair-before.webp", after: "/image-masking-hair-after.webp" },
  port_19: { before: "/image-masking-veil-before.webp", after: "/image-masking-veil-after.webp" },
  port_20: { before: "/image-masking-woven-before.webp", after: "/image-masking-woven-after.webp" },
  port_21: { before: "/image-masking-fur-before.webp", after: "/image-masking-fur-after.webp" },
  port_22: { before: "/shadow-reflection-hero-before.webp", after: "/shadow-reflection-hero-after.webp" },
  port_23: { before: "/shadow-reflection-speaker-before.webp", after: "/shadow-reflection-speaker-after.webp" },
  port_24: { before: "/clipping-path-sunglasses-before.webp", after: "/clipping-path-sunglasses-after.webp" },
  port_25: { before: "/shadow-reflection-sunglasses-before.webp", after: "/shadow-reflection-sunglasses-after.webp" },
  port_26: { before: "/shadow-reflection-bag-before.webp", after: "/shadow-reflection-bag-after.webp" },
  port_27: { before: "/beauty-skin-retouch-before.webp", after: "/beauty-skin-retouch-after.webp" },
  port_28: { before: "/glamour-raw-1.webp", after: "/glamour-edited-1.webp" },
  port_29: { before: "/fashion-raw-2.webp", after: "/fashion-edited-2.webp" },
  port_30: { before: "/beauty-raw-3-final.webp", after: "/beauty-edited-3-final.webp" },
  port_31: { before: "/model-retouch-full-before.webp", after: "/model-retouch-full-after.webp" },
  port_32: { before: "/model-dress-before.webp", after: "/model-dress-after.webp" },
  port_33: { before: "/model-posture-before.webp", after: "/model-posture-after.webp" },
  port_34: { before: "/model-hair-before.webp", after: "/model-hair-after.webp" },
  port_35: { before: "/model-swimsuit-before.webp", after: "/model-swimsuit-after.webp" },
  port_36: { before: "/product-retouch-electronics-before.webp", after: "/product-retouch-electronics-after.webp" },
  port_37: { before: "/product-retouch-leather-before.webp", after: "/product-retouch-leather-after.webp" },
  port_38: { before: "/product-retouch-powertool-before.webp", after: "/product-retouch-powertool-after.webp" },
  port_39: { before: "/product-retouch-perfume-before.webp", after: "/product-retouch-perfume-after.webp" },
  port_40: { before: "/Jewlery-Retouch-5.webp", after: "/Jewlery-Retouch-5-Done.webp" },
  port_41: { before: "/clipping-path-ring-before.webp", after: "/clipping-path-ring-after.webp" },
  port_42: { before: "/jewelry-chain-before.webp", after: "/jewelry-chain-after.webp" },
  port_43: { before: "/jewelry-pearls-before.webp", after: "/jewelry-pearls-after.webp" },
  port_44: { before: "/color-recolor-before.webp", after: "/color-recolor-after.webp" },
  port_45: { before: "/color-silk-before.webp", after: "/color-silk-after.webp" },
  port_46: { before: "/color-boot-before.webp", after: "/color-boot-after.webp" },
  port_47: { before: "/color-suv-before.webp", after: "/color-suv-after.webp" },
  port_48: { before: "/manipulation-whiskey-before.webp", after: "/manipulation-whiskey-after.webp" },
  port_49: { before: "/manipulation-beach-before.webp", after: "/manipulation-beach-after.webp" },
  port_50: { before: "/manipulation-villa-before.webp", after: "/manipulation-villa-after.webp" },
  port_51: { before: "/manipulation-cyberpunk-before.webp", after: "/manipulation-cyberpunk-after.webp" },
  port_52: { before: "/flatlay-hero-before.webp", after: "/flatlay-hero.webp" },
  port_53: { before: "/flatlay-sport-before.webp", after: "/flatlay-sport-after.webp" },
  port_54: { before: "/flatlay-puffer-before.webp", after: "/flatlay-puffer-after.webp" },
  port_55: { before: "/flatlay-silk-before.webp", after: "/flatlay-silk-after.webp" },
  port_56: { before: "/flatlay-knit-before.webp", after: "/flatlay-knit-after.webp" },
  port_57: { before: "/handbag-before.webp", after: "/handbag-after.webp" },
  port_58: { before: "/chair-before.webp", after: "/chair-after.webp" },
  port_59: { before: "/multi-clipping-before.webp", after: "/multi-clipping-after.webp" },
  port_60: { before: "/Real-Estate-Before.webp", after: "/Real-Estate-After.webp" },
  port_61: { before: "/real-estate-twilight-before.webp", after: "/real-estate-twilight-after.webp" },
  port_62: { before: "/real-estate-hdr-before.webp", after: "/real-estate-hdr-after.webp" },
  port_63: { before: "/real-estate-staging-before.webp", after: "/real-estate-staging-after.webp" },
  port_64: { before: "/real-estate-cleanup-before.webp", after: "/real-estate-cleanup-after.webp" },
  port_65: { before: "/car-suv-before.webp", after: "/car-suv-after.webp" },
  port_66: { before: "/car-sport-before.webp", after: "/car-sport-after.webp" },
  port_67: { before: "/car-interior-before.webp", after: "/car-interior-after.webp" },
  port_68: { before: "/car-offroad-before.webp", after: "/car-offroad-after.webp" },
  port_69: { before: "/product-360-before.webp", after: "/product-360-after.webp" },
  port_70: { before: "/product-360-align-before.webp", after: "/product-360-align-after.webp" },
  port_71: { before: "/product-360-color-before.webp", after: "/product-360-color-after.webp" },
  port_72: { before: "/product-360-reflect-before.webp", after: "/product-360-reflect-after.webp" },
  port_73: { before: "/product-360-rig-before.webp", after: "/product-360-rig-after.webp" },
  port_74: { before: "/packshot-electronics-before.webp", after: "/packshot-electronics-after.webp" },
  port_75: { before: "/packshot-footwear-before.webp", after: "/packshot-footwear-after.webp" },
  port_76: { before: "/packshot-cosmetic-before.webp", after: "/packshot-cosmetic-after.webp" },
  port_77: { before: "/web-opt-before.webp", after: "/web-opt-after.webp" },
  port_78: { before: "/web-opt-compress-before.webp", after: "/web-opt-compress-after.webp" },
  port_79: { before: "/web-opt-scale-before.webp", after: "/web-opt-scale-after.webp" },
  port_80: { before: "/web-opt-seo-before.webp", after: "/web-opt-seo-after.webp" },
  port_81: { before: "/web-opt-format-before.webp", after: "/web-opt-format-after.webp" },
  port_82: { before: "/restoration-torn-before.webp", after: "/restoration-torn-after.webp" },
  port_83: { before: "/restoration-faded-before.webp", after: "/restoration-faded-after.webp" },
  port_84: { before: "/restoration-mold-before.webp", after: "/restoration-mold-after.webp" },
  port_85: { before: "/restoration-color-before.webp", after: "/restoration-color-after.webp" },

    beauty:   { before: "/hero-beauty-before.png",            after: "/hero-beauty-after.png" },
    beauty2:  { before: "/image-masking-hair-before.webp",          after: "/image-masking-hair-after.webp" },
    color:    { before: "/clipping-path-espresso-before-wide.png",      after: "/clipping-path-espresso-after-wide.png" },
    correct:  { before: "/product-retouch-electronics-before.webp", after: "/product-retouch-electronics-after.webp" },
    ecom:     { before: "/hero-ecom-before-wide.png",                after: "/hero-ecom-after-wide.png" },
    clip:     { before: "/hero-clip-before-v6.png",                after: "/hero-clip-after-v9.png" },
    mannequin:{ before: "/hero-mannequin-before-v7.png",           after: "/hero-mannequin-after-v7.png" },
    masking:  { before: "/hero-masking-before-wide.png",             after: "/hero-masking-after-wide.png" },
    shadow:   { before: "/shadow-reflection-hero-before-wide.png",      after: "/shadow-reflection-hero-after-wide.png" },
    model:    { before: "/beauty-skin-retouch-before.webp",         after: "/beauty-skin-retouch-after.webp" },
    product:  { before: "/product-retouch-electronics-before.webp", after: "/product-retouch-electronics-after.webp" },
    jewelry:  { before: "/Jewelry-Retouch-5.webp",                  after: "/Jewelry-Retouch-5-Done.webp" },
  },

  // 9 services — ids + exact URLs from the live site
  services: [
    {
      id: "ecom", no: "01", short: "E-commerce Edit", name: "E-commerce\nImage Editing",
      url: "/e-commerce-edit", pair: "ecom", fit: "cover", related: ["clipping", "shadow", "product"],
      price: "from €0.35/image",
      blurb: "Marketplace-ready imagery — cropped, aligned, shadowed and spec-compliant at scale.",
      intro: {
        definition: "E-commerce image editing is the professional post-processing of product photos to meet marketplace technical requirements — correct background colour, crop ratios, and file specifications for Amazon, Shopify, eBay, and Etsy.",
        whyItMatters: "Inconsistent product images reduce conversion rates. A pure-white background (RGB 255,255,255) is required by Amazon for main images; off-white or grey backgrounds cause listing suppression. Consistent crop margins ensure uniform thumbnail grids across catalog pages.",
      },
      long: "Inconsistent product images are a quiet revenue killer. Slightly different lighting, varying crop ratios, backgrounds that almost-but-not-quite match — buyers notice, even when they can't say why. BLACKFOX DIGITAL processes catalog batches as uniform sets: identical white-point adjustments, crop margins, and output dimensions across every SKU. All images meet Amazon FBA (pure white RGB 255,255,255), Shopify, eBay, and Etsy technical requirements. Every image is edited by a human specialist — not processed by AI. Starting from €0.35 per image, with standard 24-hour delivery.",
      features: [
        ["Spec compliant", "Meets Amazon, Shopify, eBay and Etsy image requirements out of the box."],
        ["Batch consistency", "Every SKU receives identical white point, crop margin and output dimensions."],
        ["Human-edited", "No AI shortcuts — every file handled by a trained specialist."],
      ],
      whoFor: "E-commerce brands, Amazon and Shopify sellers, and product photographers who need consistent, marketplace-ready images at scale — from a single SKU to tens of thousands.",
      pricingTiers: [
        { tier: "Simple",  description: "Single product, solid background, minimal clipping",       price: "from €0.35" },
        { tier: "Medium",  description: "Multiple products or props, moderate complexity",           price: "from €0.55" },
        { tier: "Complex", description: "Composites, multiple crops, lifestyle scenes",             price: "from €0.85" },
        { tier: "Bulk",    description: "500+ images/month — volume rate applied automatically",    price: "Contact us" },
      ],
      faq: [
        { q: "What background colour do Amazon and eBay require?", a: "Amazon main images require a pure white background (RGB 255, 255, 255) filling at least 85% of the frame. eBay and Shopify also default to white. We deliver all files pre-set to your exact marketplace spec." },
        { q: "Can you match our existing catalog style across a new batch?", a: "Yes. Send us 3–5 reference images representing your current standard and we build a style guide for your account. Every new batch matches it automatically." },
        { q: "Is there a minimum order size?", a: "No minimum. You can send a single image or 10,000. Per-image rates apply from the first file with no setup fee." },
        { q: "How do you handle different crop ratios for different platforms?", a: "We deliver multiple crop variants from a single order. Specify your required pixel dimensions and margin ratios for each platform (Amazon, Shopify, print) and we'll output all variants together." },
      ],
    },
    {
      id: "clipping", no: "02", short: "Background Removal", name: "Background Removal\n& Clipping Path",
      url: "/background-removal-clippingpath-service", pair: "clip", fit: "cover", related: ["masking", "shadow", "ecom"],
      price: "from €0.25/image",
      blurb: "Hand-drawn pen-tool paths for pixel-clean cut-outs and seamless background swaps.",
      intro: {
        definition: "A clipping path is a vector path hand-drawn around a product using Photoshop's pen tool, used to remove or replace the background. Background removal is the process of applying that path to produce a clean cut-out — transparent PNG, white JPEG, or a custom replacement background.",
        whyItMatters: "Unlike automated background removal tools, a hand-drawn clipping path preserves edge sharpness at full print resolution and produces no fringing or halo artefacts around the subject.",
      },
      long: "Background removal and clipping path are the foundation of e-commerce and product photography post-production. Every path at BLACKFOX is hand-drawn with the pen tool — no auto-select, no AI fill, no shortcuts. The result is a clean, anti-aliased edge at full print resolution that holds up whether you're printing at A0 or serving a 400px thumbnail on a marketplace. We deliver transparent PNGs, Amazon-compliant white JPEGs, and layered PSDs with named paths — whichever format fits your workflow. From simple geometric products to complex hair and fur, every subject gets the correct technique. Starting from €0.25 per image, with 24-hour delivery.",
      features: [
        ["Pen-tool precision", "Every path hand-traced — no auto-select, no AI edges, no fringing."],
        ["Any format", "Transparent PNG, white JPEG, layered PSD or TIFF — your choice."],
        ["Simple to complex", "Single paths for basic shapes up to multi-path for intricate products."],
      ],
      whoFor: "Product photographers, e-commerce businesses, catalogue studios, and print designers who need pixel-clean cut-outs — from simple geometric products to complex hair, fur, and jewellery.",
      pricingTiers: [
        { tier: "Simple",  description: "Basic shapes, solid objects, single path",           price: "from €0.25" },
        { tier: "Medium",  description: "Multiple paths, moderate edge complexity",           price: "from €0.45" },
        { tier: "Complex", description: "Hair, fur, jewellery, wire mesh, multi-path",        price: "from €0.75" },
        { tier: "Bulk",    description: "500+ images/month — volume rate",                    price: "Contact us" },
      ],
      faq: [
        { q: "What's the difference between a clipping path and background removal?", a: "A clipping path is a vector path hand-drawn around a subject using the pen tool, used for hard-edged objects. Background removal applies that path to produce a transparent or white-background output file. We use the correct technique for each subject automatically." },
        { q: "Can you handle complex subjects like chains, wire mesh, or jewellery settings?", a: "Yes. Complex multi-path subjects are priced at a higher tier but are handled with the same pen-tool technique. No subject is too intricate — send a sample and we'll quote it accurately." },
        { q: "What file formats do you deliver?", a: "Transparent PNG, Amazon-compliant white JPEG, layered PSD with named paths, and TIFF. You can request multiple formats in a single order at no extra charge." },
        { q: "Can you match a specific background colour instead of white?", a: "Yes. Specify any RGB or HEX background value and we'll fill the output to your exact colour. Custom backgrounds (lifestyle scenes, gradients) are also available on request." },
      ],
    },
    {
      id: "mannequin", no: "03", short: "Ghost Mannequin", name: "Ghost\nMannequin",
      url: "/ghost-mannequin", pair: "mannequin", fit: "cover", related: ["ecom", "clipping", "model"],
      price: "from €0.85/image",
      blurb: "Invisible-mannequin compositing that gives apparel a clean, 3-D hollow form.",
      intro: {
        definition: "Ghost mannequin, also called invisible mannequin or neck joint, is a post-production technique that digitally removes the mannequin from garment photographs, leaving a clean 3D hollow form that shows the fit and cut of the product without the distraction of a physical stand or model.",
        whyItMatters: "Ghost mannequin is the e-commerce standard for fashion product pages. It reduces photography costs compared to hiring models, and produces a consistent, structured silhouette that performs better in A/B tests than flat-lay or model photography for most apparel categories.",
      },
      long: "Ghost mannequin — also called invisible mannequin or neck joint — is the standard technique for fashion e-commerce. We digitally remove the physical mannequin, stitch the internal collar, lining and brand tags, and build a clean, structured 3D silhouette that shows fit and cut exactly as the customer would see the garment. Our process includes digital ironing to remove packing creases, and symmetry correction across sleeves and hems. The result is a hollow 3D form that reads immediately on any screen — consistent, cost-effective, and ready for any marketplace. Works for everything from basic tees to structured suits, outerwear, lingerie, and swimwear. Starting from €0.85 per image, 24-hour delivery.",
      features: [
        ["Neck joint stitch", "Interior collar, lining and brand labels composited cleanly every time."],
        ["3-D hollow form", "Mannequin removed, garment left with realistic volume and structure."],
        ["Digital ironing", "Packing creases removed and left/right symmetry corrected across the garment."],
      ],
      whoFor: "Fashion brands, apparel e-commerce retailers, clothing photographers, and studio owners who shoot garments and need the mannequin removed — from basic t-shirts to complex outerwear and multi-layer pieces.",
      pricingTiers: [
        { tier: "Basic",    description: "Simple garments — tees, tanks, basic tops",                price: "from €0.85" },
        { tier: "Standard", description: "Shirts, dresses, trousers, basic outerwear",              price: "from €1.20" },
        { tier: "Complex",  description: "Structured jackets, multi-layer, padded outerwear",       price: "from €1.80" },
        { tier: "Bulk",     description: "500+ garments/month — volume rate",                       price: "Contact us" },
      ],
      faq: [
        { q: "Do you need both exterior and interior shots of the garment?", a: "For a clean neck joint stitch we need the exterior and the interior (lining/collar) shots. For simple garments like lightweight t-shirts, we can sometimes work from a single exterior shot — send a sample and we'll advise." },
        { q: "Can you handle hoodies, structured jackets, and multi-layer garments?", a: "Yes. Hoodies, padded jackets and multi-layer pieces require additional compositing work, priced by complexity. They are a core part of our ghost mannequin service — nothing is too structured." },
        { q: "Is digital ironing (crease removal) included as standard?", a: "Yes. Packing crease removal and left/right symmetry correction across sleeves and hems are included in every ghost mannequin order at no additional charge." },
        { q: "What turnaround can you offer for a 500-piece fashion shoot?", a: "Standard 24-hour turnaround for batches up to 1,000 images. For 500 pieces we would deliver the full batch within 24 hours — contact us before a large shoot to confirm capacity." },
      ],
    },
    {
      id: "masking", no: "04", short: "Image Masking", name: "Image\nMasking",
      url: "/image-masking-service", pair: "masking", fit: "cover", related: ["clipping", "beauty", "model"],
      price: "from €0.75/image",
      blurb: "Hair, fur and translucency handled with alpha & channel masking — no lost detail.",
      intro: {
        definition: "Image masking is the technique used to isolate subjects with fine, complex edges — hair, fur, feathers, smoke, glass, or translucent fabrics — where a hard clipping path would clip away detail. Alpha channel masking and layer masking preserve strand-level and edge detail at the pixel level.",
        whyItMatters: "Automated masking tools produce visible fringing and lost detail on hair and fur. Manual alpha channel extraction retains individual strands and realistic edge transparency, which is critical for beauty, fashion, and pet product photography.",
      },
      long: "Image masking is the technique used when a clipping path isn't sufficient — for subjects with hair, fur, fine feathers, smoke, glass, or translucent fabrics. We use alpha channel extraction and layer masking to separate the subject from its background while keeping strand-level detail intact. No artificial edge, no halo, no lost texture. Whether you're isolating a model's curly hair for a white background, extracting a glass vase for a lifestyle composite, or separating sheer lingerie, we apply the right masking technique for each specific subject. Starting from €0.75 per image with 24-hour delivery.",
      features: [
        ["Hair & fur", "Strand-level detail retained — no halo, no artificial edges."],
        ["Alpha channel", "Correct technique selected per subject: alpha, channel, or layer mask."],
        ["Glass & translucency", "Smoke, glass and sheer fabric extracted with natural transparency."],
      ],
      whoFor: "Fashion and beauty photographers, composite artists, and brands that shoot subjects with hair, fur, translucent fabric, glass, or smoke — anything where a hard clipping path would destroy fine edge detail.",
      pricingTiers: [
        { tier: "Standard", description: "Hair, simple fur, semi-transparent fabric",   price: "from €0.75" },
        { tier: "Complex",  description: "Dense fur, glass, smoke, multiple subjects",  price: "from €1.20" },
        { tier: "Bulk",     description: "500+ images/month — volume rate",             price: "Contact us" },
      ],
      faq: [
        { q: "When should I use masking instead of a clipping path?", a: "Use masking when the subject has hair, fur, fine feathers, smoke, glass, or translucent fabric — anything where a hard vector path would cut off fine detail. We assess each image and apply the correct technique automatically." },
        { q: "Can you mask subjects on complex or busy backgrounds?", a: "Yes, though detailed backgrounds (outdoor scenes, textured walls) take longer to mask cleanly. Send a sample image and we'll assess it and quote accurately before you commit." },
        { q: "Do you retain fine hair strands at full print resolution?", a: "Yes. We use alpha channel extraction at native resolution. No strand-level detail is lost and there is no halo or fringing on the output — at any print size." },
        { q: "What's the difference between alpha masking and layer masking?", a: "Alpha masking extracts fine edge detail (hair, fur) using the channel data already in the image. Layer masking is a Photoshop technique used for broader subject separation. We choose the right approach for each specific image — you don't need to specify which." },
      ],
    },
    {
      id: "shadow", no: "05", short: "Shadow & Reflection", name: "Shadow &\nReflection",
      url: "/shadow-reflection-services", pair: "shadow", fit: "cover", related: ["ecom", "clipping", "product"],
      price: "from €0.45/image",
      blurb: "Natural, drop and mirror shadows that ground products without a studio reshoot.",
      intro: {
        definition: "Shadow and reflection services add natural-looking drop shadows, cast shadows, or mirror reflections beneath product photos — creating the visual anchor that makes objects feel grounded on a white or transparent background.",
        whyItMatters: "Products photographed on white backgrounds without shadows can look artificially 'floating' or pasted-in. A correctly drawn drop shadow or reflection increases perceived product quality and click-through rate on marketplace listings.",
      },
      long: "Once a background has been removed, a product can look flat and disconnected without a shadow or reflection. BLACKFOX creates natural shadows, drop shadows, and mirror reflections — each matched to the object's geometry and the original light source in the photograph. The result is a product that looks grounded, three-dimensional, and naturally lit — without the cost of a studio reshoot. We deliver each variant separately so you can A/B test which shadow style converts best for your catalog. Starting from €0.45 per image, with 24-hour delivery.",
      features: [
        ["Natural shadow", "Built from the original light source — indistinguishable from a studio shot."],
        ["Drop shadow", "Classic floating effect that lifts products off a white background."],
        ["Mirror reflection", "Floor and surface reflections matched to the object's geometry."],
      ],
      whoFor: "Product photographers, e-commerce brands, and catalogue studios whose products look flat or disconnected after background removal — and need a realistic shadow or reflection added without a studio reshoot.",
      pricingTiers: [
        { tier: "Drop shadow",    description: "Standard soft drop shadow below subject",  price: "from €0.45" },
        { tier: "Reflection",     description: "Mirror reflection on flat surface",         price: "from €0.55" },
        { tier: "Natural shadow", description: "Cast or natural light shadow compositing", price: "from €0.75" },
        { tier: "Bulk",           description: "500+ images/month — volume rate",          price: "Contact us" },
      ],
      faq: [
        { q: "What types of shadow can you create?", a: "Natural shadows (cast from the original light source direction), drop shadows (floating effect under the product), floor shadows (graduated fade beneath the object), and mirror reflections. Each is delivered as a separate layer." },
        { q: "Can you match an existing shadow style across an entire product range?", a: "Yes. Send reference images with your preferred shadow treatment and we match the direction, softness, opacity, and spread consistently across your full catalog." },
        { q: "Do you need the original unedited shot, or can you work from a cut-out?", a: "Both. We can add a shadow after background removal or to an image where the background is already white. If you're ordering background removal and shadow together, we handle both in a single workflow." },
        { q: "Can shadows be added to lifestyle images, not just white-background shots?", a: "Yes. We can add or enhance shadows on lifestyle backgrounds, composites, and coloured backgrounds. The shadow is matched to the existing ambient light in the scene." },
      ],
    },
    {
      id: "beauty", no: "06", short: "Beauty & Skin", name: "Beauty &\nSkin Retouch",
      url: "/beauty-skin", pair: "beauty", fit: "cover", related: ["model", "masking", "product"],
      price: "from €2.75/image",
      blurb: "Frequency-separation retouching that keeps skin texture natural and editorial.",
      intro: {
        definition: "Beauty and skin retouching is the high-end post-processing of portrait and beauty photography — removing blemishes, evening skin tone, enhancing eyes and lips, and correcting lighting to produce a polished, editorial-quality result.",
        whyItMatters: "For cosmetic and skincare brands, product imagery must show both the product and its effect on skin. High-end retouching that looks natural — not over-processed — is the standard for beauty editorial and marketplace imagery.",
      },
      long: "Beauty and skin retouching at BLACKFOX uses frequency separation to work on skin tone and texture independently — so blemishes, uneven colour and distractions are removed without destroying the natural pore and skin texture that makes an image look real rather than plastic. We then apply dodge and burn to sculpt the light across facial structure, bringing out the features that the photographer intended. No AI filters, no blur tools, no shortcuts — every edit is done by hand by a specialist retoucher. Suitable for beauty campaigns, fashion lookbooks, e-commerce model shots, and editorial work. Starting from €2.75 per image.",
      features: [
        ["Frequency separation", "Skin tone corrected independently from texture — no plastic-skin effect."],
        ["Blemish removal", "Spots, redness and distractions removed while preserving natural skin detail."],
        ["Dodge & burn", "Light sculpted across facial structure for a controlled, editorial finish."],
      ],
      whoFor: "Beauty brands, cosmetics campaigns, fashion lookbooks, e-commerce model shots, and photographers who need skin to look natural and editorial — not over-processed or artificially smooth.",
      pricingTiers: [
        { tier: "Standard", description: "Colour correction, minor blemishes, basic skin smoothing",              price: "Contact us" },
        { tier: "High-end", description: "Full editorial retouch, compositing, detailed skin and hair work",      price: "Contact us" },
        { tier: "Campaign", description: "Campaign-level retouching, multiple looks, delivery to spec",           price: "Contact us" },
      ],
      faq: [
        { q: "Will the retouching look natural or over-edited?", a: "Natural. Frequency separation keeps the underlying skin texture intact while correcting tone and removing blemishes. The result is never 'smooth plastic' — it looks like the model in perfect light, not a filter." },
        { q: "Can you match a specific retouching style or reference images?", a: "Yes. Send three to five reference images that represent your current standard and we build a dedicated style guide for your account. Every image we deliver matches your reference set." },
        { q: "Do you retouch body as well as face?", a: "Yes. Full-body retouching — contouring, body correction, clothing wrinkle removal, and hair — is included on request. Brief us clearly on which areas to address and to what degree." },
        { q: "What's the difference between beauty retouching and model retouching?", a: "Beauty retouching focuses on the face — skin, blemishes, dodge and burn. Model retouching is a full-frame correction that also covers hair, garment drape, background clean-up and a colour grade. See our Model Retouch service for full-frame work." },
      ],
    },
    {
      id: "model", no: "07", short: "Model Retouch", name: "Model\nRetouch",
      url: "/model-retouch", pair: "model", fit: "cover", related: ["beauty", "masking", "mannequin"],
      price: "from €3.50/image",
      blurb: "Glamour and high-end retouching for fashion, beauty and campaign work.",
      intro: {
        definition: "Model retouching is the professional post-processing of fashion photography featuring human models — correcting posture, wardrobe, hair, and background to produce clean, brand-consistent editorial and e-commerce imagery.",
        whyItMatters: "On-figure photography consistently outperforms flat-lay for fashion conversion rates, but requires retouching to remove shooting artefacts, garment imperfections, and environmental distractions that would otherwise require a reshoot.",
      },
      long: "Model retouching goes beyond skin — it's a full-frame correction tuned to your campaign and brand standard. Skin is retouched with frequency separation, stray hairs are removed or tamed, garment drape is corrected, and the final colour grade is matched to your creative brief. Whether you're shooting a fast-fashion lookbook or a luxury campaign, the output is consistent across the full shoot. Send three to five reference images representing your current editing standard and we'll build a dedicated style guide for your account. Starting from €3.50 per image with 24-hour delivery.",
      features: [
        ["Full-frame correction", "Skin, hair, garment drape and background all treated in one pass."],
        ["Style-matched grade", "Colour grade matched to your campaign — send reference images to brief us."],
        ["Stray hair & detail", "Flyaways tamed, unwanted creases removed, consistency held across the shoot."],
      ],
      whoFor: "Fashion brands, campaign agencies, and photographers shooting lookbooks, e-commerce ranges, or editorial work who need full-frame consistency across an entire shoot — not just clean skin.",
      pricingTiers: [
        { tier: "Standard", description: "Posture and wardrobe correction, background clean-up",                 price: "Contact us" },
        { tier: "High-end", description: "Full model retouch — skin, hair, wardrobe, environment",               price: "Contact us" },
        { tier: "Campaign", description: "Campaign-level editorial, multi-look delivery, art-direction notes",   price: "Contact us" },
      ],
      faq: [
        { q: "How is model retouching different from beauty retouching?", a: "Model retouching is a full-frame correction — skin, hair, garment drape, background clean-up, and a colour grade matched to your campaign. Beauty retouching focuses on the face only. Both use frequency separation but model work covers the entire image." },
        { q: "Can you maintain consistency across 200 images from the same shoot?", a: "Yes. We build a style guide from your reference images and apply it identically across the full shoot. Skin tone, grade, and correction level are consistent from image one to image two hundred." },
        { q: "Do you include colour grading as part of the retouch?", a: "Yes. Colour grade is included in every model retouch order. Send your reference grade or Lightroom preset and we match it across the full set at no additional cost." },
        { q: "What briefing do you need before starting a large shoot batch?", a: "Send 3–5 reference images that represent the look you want, your preferred grade or LUT if you have one, and any specific areas to address (stray hairs, garment issues, background). We build a style guide and send a test image for approval before processing the full batch." },
      ],
    },
    {
      id: "product", no: "08", short: "Product Retouch", name: "Product\nRetouch",
      url: "/product-retouch", pair: "product", fit: "cover", related: ["ecom", "shadow", "jewelry"],
      price: "from €0.99/image",
      blurb: "Micro-level cleanup that makes products look the way they do in person.",
      intro: {
        definition: "Product retouching is the detailed enhancement of hard-goods and lifestyle product photography — removing dust, scratches, and reflections; correcting colour accuracy; and adding subtle enhancement to bring out surface texture and material quality.",
        whyItMatters: "Consumers judge product quality by image quality. A retouched product image that accurately represents colour, texture, and condition reduces return rates and increases buyer confidence, particularly for high-value items like electronics, tools, and luxury goods.",
      },
      long: "Product retouching goes beyond background removal — it's the micro-level cleanup that makes an image look the way the product does when a customer holds it in their hands. Dust, fingerprints, glare, label misalignment, surface scratches and defects are all removed. Colour is corrected to brand spec. The final image is sharp, even, and catalog-ready — whether it's going to print or a Shopify product page. We process in batches with consistent output across your full range. Starting from €0.99 per image, delivered in 12–24 hours.",
      features: [
        ["Surface cleanup", "Dust, fingerprints, glare, scratches and label misalignment all removed."],
        ["Colour accuracy", "Corrected to true-to-life brand specification — consistent across the catalog."],
        ["Crisp finish", "Sharp, even result ready for print, e-commerce or marketplace upload."],
      ],
      whoFor: "Product brands, catalogue studios, print designers, and e-commerce operations that need products to look exactly as they do in real life — with dust, scratches, glare, and colour drift corrected to brand specification.",
      pricingTiers: [
        { tier: "Standard", description: "Dust, scratch removal, colour accuracy correction",                    price: "Contact us" },
        { tier: "High-end", description: "Full surface retouch, reflection control, material enhancement",       price: "Contact us" },
        { tier: "Campaign", description: "Campaign packshot quality — compositing, CGI integration, multi-angle", price: "Contact us" },
      ],
      faq: [
        { q: "What exactly is included in product retouching?", a: "Dust and scratch removal, colour accuracy correction to brand spec, removal of surface glare and reflections, label alignment, sharpening, and final output at your required dimensions and DPI. All corrections are applied consistently across the full catalog batch." },
        { q: "Can you match Pantone or RAL colour references?", a: "Yes. Provide a Pantone, RAL, HEX or physical swatch reference and we match output colour to your exact brand specification — critical for products where colour accuracy drives purchasing decisions." },
        { q: "Do you retouch packaging as well as physical products?", a: "Yes. Packaging retouching — boxes, bottles, cans, labels — including label alignment, foil correction, gloss removal, and crease elimination is part of our product retouch service." },
        { q: "Can you handle very large batches, for example a full season catalogue?", a: "Yes. We process batches of any size with consistent output across every image. For full season catalogues (500+ products), contact us in advance to schedule capacity and we will assign a dedicated team." },
      ],
    },
    {
      id: "jewelry", no: "09", short: "Jewelry Retouch", name: "Jewelry\nRetouch",
      url: "/jewelry-retouch", pair: "jewelry", fit: "cover", related: ["product", "clipping", "shadow"],
      price: "from €3.50/image",
      blurb: "Sparkle enhancement, dust removal and metal/gemstone clean-up for fine detail.",
      intro: {
        definition: "Jewellery retouching is the specialised post-processing of jewellery photography — enhancing gemstone brilliance, cleaning metalwork, removing micro-scratches, and perfecting reflections to produce catalogue-quality imagery from standard studio shots.",
        whyItMatters: "Jewellery photography is technically demanding because small imperfections in metal and stone are magnified at high resolution. Professional retouching is the standard for any brand selling above the mass-market tier.",
      },
      long: "Jewelry retouching demands precision that product retouching cannot cover. Camera reflections are removed from curved metal surfaces, diamond and gemstone facets are dodge-and-burned individually to restore brilliance, metal gradients are rebuilt to show the true surface quality, and focus stacking is applied for macro pieces where depth of field falls short. Colour accuracy is critical — a sapphire that renders purple instead of blue loses a sale. We deliver to your exact colour profile specification. Starting from €3.50 per image with 24–48 hour delivery.",
      features: [
        ["Facet enhancement", "Each diamond and gemstone facet dodge-and-burned to restore natural brilliance."],
        ["Reflection removal", "Camera and studio reflections removed from polished and curved metal surfaces."],
        ["Colour accuracy", "Delivered to your exact colour profile — sapphires, rubies and emeralds reproduced true."],
      ],
      whoFor: "Jewelry brands, luxury retailers, fine jewelry photographers, and e-commerce operations where gemstone brilliance, metal accuracy, and microscopic surface detail directly affect perceived value and conversion.",
      pricingTiers: [
        { tier: "Standard", description: "Micro-scratch removal, metalwork clean-up, basic stone enhancement",   price: "Contact us" },
        { tier: "High-end", description: "Gemstone brilliance, reflection perfection, full metal polish",        price: "Contact us" },
        { tier: "Campaign", description: "Catalogue-quality finish — compositing, lifestyle backgrounds, spec delivery", price: "Contact us" },
      ],
      faq: [
        { q: "Why does jewelry retouching cost more than standard product retouching?", a: "A single ring can have 30–50 individual facets that each need dodge-and-burn treatment to restore natural brilliance. Metal gradients must be rebuilt from scratch on curved surfaces. The time and precision required are significantly higher than standard product work." },
        { q: "Can you enhance diamonds and gemstones to look more brilliant?", a: "Yes. We dodge-and-burn each facet individually to restore the natural sparkle lost under studio lighting. We don't add artificial glow — we restore the real optical behaviour of the stone as it appears in natural light." },
        { q: "How do you handle gold, rose gold, and silver tones in the same piece?", a: "Each metal tone is retouched to its correct colour temperature separately and blended at the point where metals meet. Gold warmth, rose gold pink tone, and silver coolness are each corrected and kept visually distinct." },
        { q: "Do you perform focus stacking for macro jewelry photography?", a: "Yes. For macro shots where depth of field is insufficient to keep the full piece sharp, we composite multiple focus-bracketed exposures into a single fully-sharp image. Brief us on this requirement when submitting your files." },
      ],
    },
  ],

  // hero quick-access services (matches the live site's hero icon grid)
  heroQuick: [
    { id: "clipping",  icon: "clipping",  label: "Clipping Path" },
    { id: "masking",   icon: "masking",   label: "Masking" },
    { id: "mannequin", icon: "mannequin", label: "Ghost Mannequin" },
    { id: "model",     icon: "retouch",   label: "Retouching" },
    { id: "beauty",    icon: "color",     label: "Beauty & Skin" },
    { id: "ecom",      icon: "ecom",      label: "E-commerce Edit" },
  ],

  // gallery of before/after compare cards — every row uses a matched before/after pair
  serviceGallery: [
    { title: "E-commerce Image Editing", before: "/ecommerce-jacket-before-card.webp",         after: "/ecommerce-jacket-after-card.webp",         fit: "cover", sid: "ecom" },
    { title: "Clipping Path",            before: "/hero-clip-before-v6-card.png",              after: "/hero-clip-after-v9-card.png",              fit: "cover", sid: "clipping" },
    { title: "Ghost Mannequin",          before: "/ghost-mannequin-hero-before-card.webp",     after: "/ghost-mannequin-hero-after-card.webp",     fit: "cover", sid: "mannequin" },
    { title: "Beauty & Skin Retouch",    before: "/beauty-skin-retouch-before-card.webp",      after: "/beauty-skin-retouch-after-card.webp",      fit: "cover", sid: "beauty" },
    { title: "Image Masking",            before: "/image-masking-hair-before-card.webp",       after: "/image-masking-hair-after-card.webp",       fit: "cover", sid: "masking" },
    { title: "Shadow & Reflection",      before: "/shadow-reflection-hero-before-card.webp",   after: "/shadow-reflection-hero-after-card.webp",   fit: "cover", sid: "shadow" },
    { title: "Model Retouch",            before: "/hero-beauty-before-card.png",               after: "/hero-beauty-after-card.png",               fit: "cover", sid: "model" },
    { title: "Product Retouch",          before: "/product-retouch-electronics-before-card.webp", after: "/product-retouch-electronics-after-card.webp", fit: "cover", sid: "product" },
    { title: "Jewelry Retouch",          before: "/Jewelry-Retouch-5-card.webp",               after: "/Jewelry-Retouch-5-Done-card.webp",         fit: "cover", sid: "jewelry" },
  ],

  promises: [
    { k: "01", icon: "quality",  t: "Quality Assurance", d: "Every file passes a senior-editor QC review before delivery. We don't ship until it meets your brief." },
    { k: "02", icon: "price",    t: "Transparent Pricing", d: "Per-image rates from €0.25 — no setup fees, no surprises. Volume discounts up to 20% on 1,000+ images." },
    { k: "03", icon: "delivery", t: "On-Time Delivery",  d: "Standard 24h, Rush 12h, Super Rush 6h. Hard deadlines we actually keep." },
    { k: "04", icon: "free",     t: "5 Free Edits",      d: "Send up to 5 images and we'll retouch them free — no credit card, no commitment required." },
    { k: "05", icon: "support",  t: "24/7 Support",      d: "A dedicated support manager available on WhatsApp, Skype and email across every time zone." },
  ],

  founders: [
    {
      name: "Mohammed Raihan",
      role: "Co-founder & Head of Production",
      email: "raihan@blackfoxdigital.com.bd",
      linkedin: "https://www.linkedin.com/in/raihan90",
      schemaId: "https://blackfoxdigital.com.bd/#founder-raihan",
      bio: "Mohammed Raihan has led BLACKFOX DIGITAL's production since founding in 2016, building the 80+ specialist team.",
    },
    {
      name: "Tanvir Mahedi",
      role: "Co-founder & Client Relations",
      email: "shakkhor@blackfoxdigital.com.bd",
      linkedin: "https://www.linkedin.com/in/shakkhor666/",
      schemaId: "https://blackfoxdigital.com.bd/#founder-mahedi",
      bio: "Tanvir Mahedi oversees client relationships and quality assurance across all European accounts.",
    },
  ],

  trustStats: [
    { value: "80+",   label: "In-house designers" },
    { value: "2016",  label: "Founded" },
    { value: "24h",   label: "Standard turnaround" },
    { value: "9",     label: "Post-production services" },
  ],

  workflow: [
    { k: "01", t: "Secure Upload", d: "Send files via FTP, Dropbox, WeTransfer or Google Drive. We confirm receipt and start within 2 hours." },
    { k: "02", t: "Specialist Edit", d: "A dedicated team edits your images — not generalists. Your brief and brand guidelines drive every decision." },
    { k: "03", t: "QC Review", d: "A senior editor reviews every file independently before delivery. We fix issues before you see them." },
    { k: "04", t: "Encrypted Delivery", d: "Approved files are pushed to your secure transfer of choice — FTP, Dropbox, or Google Drive." },
    { k: "05", t: "Ready to Publish", d: "You receive an instant notification. Files are in your required format, named and organized." },
  ],

  // "Feel the astonishing difference" section
  difference: {
    title: "Human-edited.\nEvery single file.",
    sub: "No AI shortcuts. No batch filters. Just skilled retouchers.",
    body: [
      "Every image that leaves our studio has been touched by a human specialist — not processed by an algorithm. That's what makes the difference visible.",
      "4.8M+ images delivered. 500+ active clients. 30 countries. The same standard on image one and image ten thousand.",
    ],
    bulkPct: "20%",
    bulkLine: "On bulk orders",
    bulkBody: "Order 1,000+ images and save 20% across all editing categories. No commitment required — just better rates at scale.",
  },

  stats: [
    { n: "80+",    l: "In-house editors" },
    { n: "4.8M+",  l: "Images delivered" },
    { n: "500+",   l: "Active clients" },
    { n: "30+",    l: "Countries served" },
  ],

  // Testimonials (from theblackfoxstudio.com)
  testimonials: [
    { q: "BLACKFOX DIGITAL transformed our entire Amazon product catalog. Turnaround was 24 hours and quality was exceptional.", name: "James R.", title: "E-Commerce Manager", location: "United Kingdom" },
    { q: "We process 2,000+ fashion images monthly with BLACKFOX DIGITAL. Their ghost mannequin work is the best we have found globally.", name: "Sophie M.", title: "Creative Director", location: "United Kingdom" },
    { q: "Reliable, fast and pixel-perfect every time. Our jewelry retouching has never looked better.", name: "Lars K.", title: "Brand Manager", location: "Germany" },
    { q: "We outsource all our background removal to BLACKFOX DIGITAL. 500+ images weekly, always delivered on time with zero errors.", name: "Michael T.", title: "Operations Director", location: "United Kingdom" },
    { q: "The clipping path quality is outstanding. Sharp edges, clean paths — exactly what our catalog needs for print and web.", name: "Anna K.", title: "Art Director", location: "Netherlands" },
    { q: "Their beauty retouching is world-class. Our model images look editorial-quality every single time.", name: "Isabella F.", title: "Fashion Photographer", location: "Italy" },
    { q: "Fast, affordable and incredibly consistent. BLACKFOX DIGITAL handles our entire Shopify product catalog monthly.", name: "Thomas B.", title: "Store Owner", location: "Germany" },
    { q: "Best image editing partner we have worked with in 8 years. Quality is consistent, pricing is fair and delivery is fast.", name: "Kevin O.", title: "Photo Studio Owner", location: "United Kingdom" },
  ],

  // About page copy
  about: {
    founders: [
      { name: "Mohammed Raihan", role: "Co-founder", email: "raihan@blackfoxdigital.com.bd", linkedin: "https://www.linkedin.com/in/raihan90" },
      { name: "Tanvir Mahedi",   role: "Co-founder", email: "shakkhor@blackfoxdigital.com.bd", linkedin: "https://www.linkedin.com/in/shakkhor666/" },
    ],
    story: [
      "BLACKFOX DIGITAL was founded in 2016 by Mohammed Raihan and Tanvir Mahedi in Dhaka, Bangladesh — starting with a team of five graphic designers and a single goal: deliver the kind of image post-production quality that European e-commerce brands couldn't find closer to home.",
      "Our team is built from talented, skilled, creative, self-motivated and organized people from different backgrounds. This diversity helps us create new and exclusive content to satisfy — and sometimes exceed — our clients' expectations. We believe client support is as important as delivering timely, qualitative end-to-end solutions.",
      "Today we are a team of more than 80 specialist editors, successfully providing clients with their post-production needs across 30+ countries. Our goal is to provide the best quality-assured output for our clients, following their instructions, and we always appreciate feedback.",
      "When a buyer reaches us we first give a free trial — up to 5 images, no payment required — to understand their requirement. After a brief discussion, our team takes the best approach and completes the files within 24 to 48 hours, delivering on the desired deadline while ensuring quality through our multi-tier quality-control process.",
      "We provide world-class professional photo editing focused on Europe — UK, Germany, France, the Netherlands, Italy and beyond. Our clients are in the fashion industry, photography, brand stores and online stores — and we use up-to-date software including Adobe Photoshop CC and Illustrator to deliver the best output.",
    ],
    why: [
      "Quality is our first priority — every file passes an independent QC desk",
      "24/7 support via WhatsApp, Skype and email in every time zone",
      "Human-edited, always — no AI shortcuts or batch filters",
      "We deliver on time. Standard 24h, Rush 12h, Super Rush 6h.",
      "Encrypted file transfer and NDA signed on request",
    ],
  },

  faq: [
    { q: "Do you offer a free trial?", a: "Yes. We edit up to 5 of your own images completely free — no credit card, no commitment. Submit via our free trial page and we'll deliver within 24–48 hours." },
    { q: "How much does photo editing cost?", a: "Pricing starts from €0.25/image for clipping path and €0.35/image for background removal, up to €3.50/image for jewelry or model retouching. Most e-commerce clients pay €0.35–€1.00 per image." },
    { q: "How fast can you process 1,000+ images?", a: "For orders up to 1,000 images we guarantee a 24-hour turnaround. We have capacity for 10,000+ images per week without compromising quality — we scale a dedicated team to your volume." },
    { q: "Do your edits meet Amazon and eBay image requirements?", a: "Yes — it's one of our most requested services. We deliver pure white backgrounds at RGB 255,255,255 in JPEG format, with precise crop margins that meet Amazon FBA and eBay Seller Central specifications." },
    { q: "Do you offer volume discounts?", a: "Yes. We offer tiered discounts: 10% for 101–500 images per month, 15% for 501–1,000, and 20% for 1,000+ images per month. No minimum order is required." },
    { q: "What file formats do you deliver in?", a: "We deliver in any format you need: JPEG, PNG (with or without transparent background), PSD with named paths, TIFF, and WebP. Multiple output variants can be included in a single order." },
    { q: "How do I send my images?", a: "Via FTP, Dropbox, Google Drive, WeTransfer, or any file-sharing platform you already use. We confirm receipt and start within 2 hours." },
    { q: "Do you sign an NDA?", a: "Yes. For clients working with exclusive product imagery, seasonal collections, or unreleased fashion photography, we sign a non-disclosure agreement before any work begins." },
    { q: "What is your revision policy?", a: "If the delivered images do not match the original specifications you provided, revisions are completed at no additional charge. Changes to the original brief may incur additional costs." },
    { q: "Do you work on RAW files?", a: "Yes — we work on CR2, NEF, ARW, DNG and all other major RAW formats. Working from RAW gives us significantly more editing latitude for colour correction and retouching." },
  ],
};

// Gallery categories — reuse available pairs
BF.gallery = [
  { name: "E-Commerce Edit", items: ["port_0","port_1","port_2","port_3"] },
  { name: "Background Removal", items: ["port_4","port_5","port_6","port_7","port_8","port_9","port_10","port_11","port_12"] },
  { name: "Ghost Mannequin", items: ["port_13","port_14","port_15","port_16","port_17"] },
  { name: "Image Masking", items: ["port_18","port_19","port_20","port_21"] },
  { name: "Shadow & Reflection", items: ["port_22","port_23","port_24","port_25","port_26"] },
  { name: "Beauty & Skin", items: ["port_27","port_28","port_29","port_30"] },
  { name: "Model Retouch", items: ["port_31","port_32","port_33","port_34","port_35"] },
  { name: "Product Retouch", items: ["port_36","port_37","port_38","port_39"] },
  { name: "Jewelry Retouch", items: ["port_40","port_41","port_42","port_43"] },
];
